version: "3"
services:
  restapi:
    image: sawny/sjchat-restapi:stable
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "1.0"
          memory: 500M
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - "8080:8080"
    networks:
      - webnet
    depends_on:
      - message-service
      - user-service

  message-service:
    image: sawny/sjchat-message-service:stable
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "1.0"
          memory: 200M
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - "50052:50052"
    networks:
      - webnet

  user-service:
    image: sawny/sjchat-user-service:stable
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "1.0"
          memory: 200M
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - "50051:50051"
    networks:
      - webnet

  web-client:
    image: sawny/sjchat-web-client:stable
    deploy:
      replicas: 2
    ports:
      - "8082:80"
    networks:
      - webnet

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8081:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
networks:
  webnet: