version: "3"
services:
  restapi:
    image: sjchat-restapi
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1.0"
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - "8080:8080"
    networks:
      - webnet
    depends_on:
      - message-service
      - user-service

  message-service:
    image: sjchat-message-service
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1.0"
          memory: 200M
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - "50052:50052"
    networks:
      - webnet
    depends_on:
      - database
      - user-service
  
  database:
    image: mongo:3.4.4
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    ports:
      - "27017:27017"
    networks:
      - webnet

  user-service:
    image: sjchat-user-service
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1.0"
          memory: 200M
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - "50051:50051"
    networks:
      - webnet
    depends_on:
      - database

  web-client:
    image: sjchat-web-client
    ports:
      - "8082:80"
    networks:
      - webnet

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8081:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
networks:
  webnet:
